modLoader = "kotlinforforge"
loaderVersion = "[4,)"
license = "All rights reserved"
#issueTrackerURL="https://change.me.to.your.issue.tracker.example.invalid/" #optional

[[mods]]
modId = "saomclib" #mandatory
version = "${file.jarVersion}"
displayName = "SAOMCLib"
# A URL to query for updates for this mod. See the JSON update specification https://mcforge.readthedocs.io/en/latest/gettingstarted/autoupdate/
#updateJSONURL="https://change.me.example.invalid/updates.json" #optional
# A URL for the "homepage" for this mod, displayed in the mod UI
#displayURL="https://change.me.to.your.mods.homepage.example.invalid/" #optional
#logoFile="saomclib.png" #optional
credits = "Thanks Jared & co for the multiloader template"
authors = "Bluexin, Tencao"
description = '''
Library mod for handling party-related features
'''

[[dependencies.saomclib]]
modId = "forge"
mandatory = true
versionRange = "[45,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.saomclib]]
modId = "minecraft"
mandatory = true
versionRange = "[1.19.4,1.20)"
ordering = "NONE"
side = "BOTH"
