language: java
install:
  - ./gradlew setupCIWorkspace
  -  sed -i 's:^[ \t]*mod_version[ \t]*=\([ \t]*.*\)$:mod_version=\1-SNAPSHOT:' gradle.properties
script:
  - ./gradlew build
before_cache:
  - rm -f $HOME/.gradle/caches/modules-2/modules-2.lock
cache:
  directories:
    - $HOME/.gradle
    - .gradle
    - gradle
jdk:
  - oraclejdk8
after_success:
  - if [ "$TRAVIS_PULL_REQUEST" == "false" ]; then ./gradlew uploadArchives; fi
  - wget https://raw.githubusercontent.com/k3rn31p4nic/travis-ci-discord-webhook/master/send.sh
  - chmod +x send.sh
  - ./send.sh success $WEBHOOK_URL
after_failure:
  - wget https://raw.githubusercontent.com/k3rn31p4nic/travis-ci-discord-webhook/master/send.sh
  - chmod +x send.sh
  - ./send.sh failure $WEBHOOK_URL
